### PR TITLE
Graceful handing of non-SSA PDFs

### LINKED ISSUE #184: Graceful handing of non-SSA PDFs
The app supports PDFs from SSA.gov but not all PDFs. It crashes on some non-SSA PDFs. Even if we don't read the PDF, we should prevent this crash.

### PR DESCRIPTION
**Pull request by shivam2407**
The behavior after this PR is merged can be seen in the below video.
https://www.loom.com/share/cf8fd7425eee45cba84e630e1ce8ab27 

closes #184

### CODE REVIEW

File: src/components/file-upload.tsx [hunk 1]
```diff
@@ -270,8 +270,8 @@ class FileUpload extends React.Component<FileUploadProps, FileUploadState> {
     if (reader.target === null || reader.target.result === null) return
     //Returns first page of document
     var combinedValues = [];
+    let earningsPage = "";
```
Comment (thadk) [inline src/components/file-upload.tsx:273]: Can we either:
- revert that line so it is `undefined` for earningsPage initial setting and then check for `undefined`, instead of `""` in the if statement on 291, 
- or set it to `undefined` in the if statement?

image

"" appears as 0 under the upload button I think.

**Review by thadk — CHANGES_REQUESTED** [review]
Tiny tweak please, so we don't regress at all.

File: src/components/file-upload.tsx (hunk 1 above)
Comment (thadk) [reply src/components/file-upload.tsx:273]: This didn't fix it after all, hmm. Tricky.

**Review by thadk — COMMENTED** [review]
Oops the zero appearing that I noticed before was coming from this: https://github.com/codeforboston/windfall-elimination/commit/cd7f16e8aa3e9c9cecaf1593e14696ea4b380179

**Review by thadk — COMMENTED** [review]
Thanks a lot! Great commit.
