### PR TITLE
Fix page crash bug related to datepicker

### LINKED ISSUE #181: When you delete date picker contents, app crashes
With the latest state/context management, we noticed when the date picker gets emptied using the delete key, the app crashes and goes white, at least on Firefox.

crash

### PR DESCRIPTION
**Pull request by Kevin1192**
closes #181
Added null value check for DatePicker. Now when the user deletes the date, the page will not crash but instead stay as the previously selected date.

### CODE REVIEW

File: src/pages/prescreen-1a.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ class Prescreen1a extends React.Component<Prescreen1aProps, Prescreen1aState> {
 
   async handleDateChange(name, value) {
     const {userStateActions} = this.props
-    if (name === "birthDatePicked") {
+    if (value && name === "birthDatePicked") {
```
Comment (paavanb) [inline src/pages/prescreen-1a.tsx:54]: If `value` is not defined, then we should `setBirthDate(null)` and `setRetireDate(null)` so that it properly clears out the field!

Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: I see. That makes sense.

Comment (thadk) [reply src/pages/prescreen-1a.tsx:54]: Hi Kevin, can you please make that change so we can merge this.

**Review by thadk — CHANGES_REQUESTED** [review]
See above: https://github.com/codeforboston/windfall-elimination/pull/182/files#r407200878

File: src/pages/prescreen-1a.tsx (hunk 1 above)
Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: Screen Shot 2020-04-12 at 10 51 34 AM

I tried to change `setBirthDate(null)` and `setRetireDate(null)` but the crash persisted.

The problem seems to be that `setBirthDate()` does not take 'null' as it's parameters. It only accepts type "Date"

Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: Is there a specific null value for Date in this case?

Comment (paavanb) [reply src/pages/prescreen-1a.tsx:54]: > The problem seems to be that setBirthDate() does not take 'null' as it's parameters. It only accepts type "Date"

Yep, see the comment I made [here!](https://github.com/codeforboston/windfall-elimination/issues/181#issuecomment-611187514) Basically, we need to update the `UserStateActions` interface to accept `null` as an argument, like so:
```
setBirthDate: (date: Date | null) => void
setRetireDate: (date: Date | null) => void
```

Then, you'll probably get an error in `user-state-manager.tsx`, which you'll likely have to update as follows:
```
setBirthDate: date => setBirthDate(date ? startOfDay(date) : null),
setRetireDate: date => setRetireDate(date ? startOfDay(date) : null)
```

Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: That worked. Thank you very much. 
Screen Shot 2020-04-12 at 4 19 30 PM
Now when the date is deleted, there is an annoying NaN below the DatePicker. I will try to get rid of it and then commit the change.

Comment (paavanb) [reply src/pages/prescreen-1a.tsx:54]: Hm strange, because the `DatePicker` component should allow `null` as a value. Maybe try setting the value to `undefined` if `birthDate === null`? Let me know what you find out!

Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: It seems that dayjs(dateOfBirth) will turn null into Invalid Date. 
I fixed it by adding a condition check. And the NaN is gone.
Screen Shot 2020-04-12 at 5 01 01 PM

That's the easiest way I can think of. But let me know if there is a better fix.  :)

Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: Also, I'm really not familiar with Github pull requests. 
I've committed a new change. But is there anything else I need to do? Should I create another pull request?

Comment (paavanb) [reply src/pages/prescreen-1a.tsx:54]: Ah, that makes sense. I think a simpler solution would be to avoid changing `this.setRetireDate` at all and simply call `userStateActions.setRetireDate(null)` directly on [line 64](https://github.com/codeforboston/windfall-elimination/pull/182/files#diff-a2ec762a64d429851a563ab208373d53R64) within `handleDateChange`. What do you think?

Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: The less code, the better. That makes the code much cleaner.

Do I need to do anything other than commit to finish this pull request?

Comment (paavanb) [reply src/pages/prescreen-1a.tsx:54]: Nope, I think you're all set! Once we can confirm everything works as expected we'll go ahead and approve and merge your PR.

Comment (Kevin1192) [reply src/pages/prescreen-1a.tsx:54]: Awesome. Thanks for the help. Much appreciated.

**Review by paavanb — APPROVED** [review]
Looks good to me, thanks for all the work! I'll let @thadk unblock and merge.

**Review by thadk — APPROVED** [review]
Tried it out, works great
